### ISSUE TITLE
Uncaught Error: hexAddress should be passed as a Buffer

### ISSUE THREAD

**Issue by MrJackdaw** [reach-sh/reach-lang#199]
I understand this has been reported, and am creating an issue to help track it as suggested. 

### Issue
Although the `.rsh` file compiles with no failures, the following error is encountered when running the app in the browser:

```
Uncaught Error: hexAddress should be passed as a Buffer
```

<img width="832" alt="Screen Shot 2021-06-26 at 6 10 04 PM" src="https://user-images.githubusercontent.com/6107109/123529901-bf2ac380-d6a9-11eb-85a5-e2cd26e510cf.png">

### Context
Encountered while building a Reach application inspired by the [NFT Dumb](https://github.com/reach-sh/reach-lang/blob/master/examples/nft-dumb/index.rsh) example. Tested as far back as `rc-46` of stdlib. 
File contents below. 

```javascript
"reach 0.1";

const AuctionProps = Object({
  assetId: UInt,
  description: Bytes(128),
  price: UInt,
});

const BuyerProps = {
  getBid: Fun([UInt], UInt),
  getNewOwner: Fun([], Address),
  showSaleItem: Fun([], Null),
};

const OwnerInterface = {
  getSaleProps: Fun([], AuctionProps),
  ...BuyerProps,
};

export const main = Reach.App(() => {
  const Owner = Participant("Owner", OwnerInterface);
  const Buyer = ParticipantClass("Buyer", BuyerProps);
  const vNFTSale = View("vNFTSale", {
    assetId: UInt,
    description: Bytes(128),
    owner: Address,
    price: UInt,
  });
  deploy();

  Owner.only(() => {
    const props = declassify(interact.getSaleProps());
  });
  Owner.publish(props);

  vNFTSale.assetId.set(props.assetId);
  vNFTSale.description.set(props.description);
  vNFTSale.owner.set(Owner);
  vNFTSale.price.set(props.price);

  var owner = Owner;
  invariant(balance() == 0);
  while (owner == Owner) {
    commit();

    Buyer.only(() => {
      // Show what's on sale (allows the front-end to use vNFTSale)
      interact.showSaleItem();

      const amOwner = this == owner;
      // Allow Owner to specify a receiver address directly, and pay nothing
      const price = amOwner ? 0 : declassify(interact.getBid(props.price));
      const newOwner = amOwner ? declassify(interact.getNewOwner()) : this;
    });

    Buyer.publish(price, newOwner).pay(price);
    transfer(balance()).to(Owner);

    owner = newOwner;
    continue;
  }

  commit();
  exit();
});

```

**Comment by MrJackdaw** [comment]
*Update:* rollback to `rc-58` works as a stop-gap.

**Comment by DanBurton** [comment]
This should be fixed as of `0.1.2-rc.64`; can you give it a try and let us know if that works for you?

**Comment by MrJackdaw** [comment]
Well the _good_ news is -- the first error disappeared. 

The bad news? It changed. 😕 

Still happens when the browser application is launched. 


<img width="830" alt="Screen Shot 2021-06-26 at 10 33 01 PM" src="https://user-images.githubusercontent.com/6107109/123533979-7d604400-d6ce-11eb-97af-a7d5a30e52eb.png">

**Comment by MrJackdaw** [comment]
@DanBurton Heya -- not sure if you saw my last response; just wanted to update that issue persists in `rc-65` (same stack trace)

**Comment by MrJackdaw** [comment]
Closing (with your blessing); issue relates to Algorand SDK and [ViteJS](https://vitejs.dev/) bundler, and [was reported to them here](https://github.com/algorand/js-algorand-sdk/issues/398).
